# -*- coding: utf-8 -*-
"""ex8_classfiication_fashion_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TW2_vmgJxJoxYRIT35Zatz3KpSsEcNIZ
"""

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam
from keras.utils import np_utils
from tensorflow.keras import datasets

(training_images, training_labels), (test_images, test_labels) = datasets.fashion_mnist.load_data()
print(training_images.shape, training_labels.shape)
print(test_images.shape, test_labels.shape)

labels = ['T_shirt', 'trouser', 'pullover', 'dress', 'coat',
          'sandal', 'shirt', 'sneaker', 'bag', 'ankle_boot']

sample_idx = np.random.randint(60000)
plt.imshow(training_images[sample_idx], cmap='gray')
plt.show()
print(labels[training_labels[sample_idx]])

training_images = training_images / 255.0 # MinMax Scaling; Normalization
test_images = test_images / 255.0
print(training_images.shape)

training_labels = np_utils.to_categorical(training_labels)
test_labels = np_utils.to_categorical(test_labels)

model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

optimizer = Adam(learning_rate=0.01)
model.compile(optimizer, loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

fit_hist = model.fit(training_images, training_labels, batch_size=256,
                     epochs=10, validation_split=0.2, verbose=1)

score = model.evaluate(test_images, test_labels, verbose=0)
print(score[1])

plt.plot(fit_hist.history['accuracy'])
plt.plot(fit_hist.history['val_accuracy'])
plt.show()

pred = model.predict(test_images)

sample_idx = np.random.randint(10000)
plt.imshow(test_images[sample_idx], cmap='gray')
print(test_labels[sample_idx])
print(pred[sample_idx])
print(labels[np.argmax(pred[sample_idx])])

